packages:
  - packages/agent-backend/typescript
  - packages/versioned-store
  - packages/index-sync
  - packages/embeddings
  - packages/ingestion
  - packages/vector-pg
  - room
  - examples/NextJS
  - examples/TSBasic

allowedBuilds: bufferutil,utf-8-validate
